sudo: required

services:
 - docker

language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"

before_install:
  - docker build -t bhish/yatda .

script:
  - npm run test
# Send coverage data to Coveralls
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
# Notify DockerHub to build the Dockerfile
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push bhish/yatda